name: Playwright Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false ensures that if WebKit fails, Chromium and Firefox will still finish running
      fail-fast: false 
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Install Playwright Browsers & OS Dependencies
      run: npx playwright install --with-deps

    - name: Reconstruct Credentials File
      run: |
            mkdir -p data
            echo '{ "validUser": { "username": "${{ secrets.SAUCE_USERNAME }}", "password": "${{ secrets.SAUCE_PASSWORD }}" } }' > data/credentials.json

    - name: Run Cucumber Tests
      # Injects the current matrix browser into the cross-env variable we set up in hooks.js
      run: npx cross-env BROWSER=${{ matrix.browser }} cucumber-js

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        # Dynamically names the artifact so you get 3 separate reports
        name: cucumber-html-report-${{ matrix.browser }} 
        path: reports/
        retention-days: 14